log_files:
  cron: "00 23 * * *" #at 23-00
  class: "CreateLogFilesScheduler"
  queue: "default"
import_retail_order:
  cron: "05 * * * *" # every 5 minute
  class: "ImportRetailOrderScheduler"
  queue: "import_retail_order"
check_refgo_order:
  cron: "05 * * * *" # every 5 minute
  class: "CheckRefgoOrderScheduler"
  queue: "check_refgo"